//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuroraVisionLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuroraVisionLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurora Vision Launcher.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNK.
        /// </summary>
        public static string AvAppDevelopmentVersion {
            get {
                return ResourceManager.GetString("AvAppDevelopmentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty rpoduct version field..
        /// </summary>
        public static string AvAppEmptyVersionField {
            get {
                return ResourceManager.GetString("AvAppEmptyVersionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed applications.
        /// </summary>
        public static string InstalledAppsPageTitle {
            get {
                return ResourceManager.GetString("InstalledAppsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line parameters.
        /// </summary>
        public static string LauncherCommandLineArgumentsSectionHeader {
            get {
                return ResourceManager.GetString("LauncherCommandLineArgumentsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with {0}.
        /// </summary>
        public static string LauncherLaunchWith {
            get {
                return ResourceManager.GetString("LauncherLaunchWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with {0} and close this launcher.
        /// </summary>
        public static string LauncherLaunchWithAndClose {
            get {
                return ResourceManager.GetString("LauncherLaunchWithAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line arguments:.
        /// </summary>
        public static string LaunchOptionsCommandLineString {
            get {
                return ResourceManager.GetString("LaunchOptionsCommandLineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level: .
        /// </summary>
        public static string LaunchOptionsExecutorLogLevelTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorLogLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log pipe:.
        /// </summary>
        public static string LaunchOptionsExecutorLogPipeTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorLogPipeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application does not have supported launch options..
        /// </summary>
        public static string LaunchOptionsNoOptions {
            get {
                return ResourceManager.GetString("LaunchOptionsNoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application does not have customizable launch options..
        /// </summary>
        public static string LaunchOptionsStudioOptions {
            get {
                return ResourceManager.GetString("LaunchOptionsStudioOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close console after finished execution.
        /// </summary>
        public static string LaunchOptiosExecutorAutoCloseTitle {
            get {
                return ResourceManager.GetString("LaunchOptiosExecutorAutoCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console mode.
        /// </summary>
        public static string LaunchOptiosExecutorConsoleModeTitle {
            get {
                return ResourceManager.GetString("LaunchOptiosExecutorConsoleModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening project.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: .
        /// </summary>
        public static string ProgramDetailsLocation {
            get {
                return ResourceManager.GetString("ProgramDetailsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string ProgramDetailsLocationFallback {
            get {
                return ResourceManager.GetString("ProgramDetailsLocationFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program name: .
        /// </summary>
        public static string ProgramDetailsProgramName {
            get {
                return ResourceManager.GetString("ProgramDetailsProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No program loaded.
        /// </summary>
        public static string ProgramDetailsProgramNameFallback {
            get {
                return ResourceManager.GetString("ProgramDetailsProgramNameFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: .
        /// </summary>
        public static string ProgramDetailsProjectType {
            get {
                return ResourceManager.GetString("ProgramDetailsProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string ProgramDetailsProjectTypeFallback {
            get {
                return ResourceManager.GetString("ProgramDetailsProjectTypeFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved with version: .
        /// </summary>
        public static string ProgramDetailsSavedWithVersion {
            get {
                return ResourceManager.GetString("ProgramDetailsSavedWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string ProgramDetailsSavedWithVersionFallback {
            get {
                return ResourceManager.GetString("ProgramDetailsSavedWithVersionFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ShellMenuFileHeader {
            get {
                return ResourceManager.GetString("ShellMenuFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ShellMenuItemFileExitHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open project....
        /// </summary>
        public static string ShellMenuItemFileSettingsOpenProject {
            get {
                return ResourceManager.GetString("ShellMenuItemFileSettingsOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ShellMenuItemFileSettingsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileSettingsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed _applications.
        /// </summary>
        public static string ShellMenuItemViewsInstalledAppsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsInstalledAppsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Launcher.
        /// </summary>
        public static string ShellMenuItemViewsLauncherPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsLauncherPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Views.
        /// </summary>
        public static string ShellMenuViewsHeader {
            get {
                return ResourceManager.GetString("ShellMenuViewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a string..
        /// </summary>
        public static string ValidationArgumentHasToBeString {
            get {
                return ResourceManager.GetString("ValidationArgumentHasToBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contains double quotes..
        /// </summary>
        public static string ValidationArgumentNoDoubleQuotes {
            get {
                return ResourceManager.GetString("ValidationArgumentNoDoubleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contains single quotes..
        /// </summary>
        public static string ValidationArgumentNoSingleQuotes {
            get {
                return ResourceManager.GetString("ValidationArgumentNoSingleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain whitespace..
        /// </summary>
        public static string ValidationArgumentNoWhitespace {
            get {
                return ResourceManager.GetString("ValidationArgumentNoWhitespace", resourceCulture);
            }
        }
    }
}
