//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuroraVisionLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuroraVisionLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurora Vision Launcher.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Learning.
        /// </summary>
        public static string AppProductTypeDeepLearningLabel {
            get {
                return ResourceManager.GetString("AppProductTypeDeepLearningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string AppProductTypeLibraryLabel {
            get {
                return ResourceManager.GetString("AppProductTypeLibraryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio Professional.
        /// </summary>
        public static string AppProductTypeProfessionalLabel {
            get {
                return ResourceManager.GetString("AppProductTypeProfessionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio Runtime.
        /// </summary>
        public static string AppProductTypeRuntimeLabel {
            get {
                return ResourceManager.GetString("AppProductTypeRuntimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file path to clipboard.
        /// </summary>
        public static string AvAppCopyPath {
            get {
                return ResourceManager.GetString("AvAppCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.
        /// </summary>
        public static string AvAppDevelopmentVersion {
            get {
                return ResourceManager.GetString("AvAppDevelopmentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty product version field..
        /// </summary>
        public static string AvAppEmptyVersionField {
            get {
                return ResourceManager.GetString("AvAppEmptyVersionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill all active processes.
        /// </summary>
        public static string AvAppKillAllProcesses {
            get {
                return ResourceManager.GetString("AvAppKillAllProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the application WITHOUT loading any program.
        /// </summary>
        public static string AvAppLaunchWithNoProgram {
            get {
                return ResourceManager.GetString("AvAppLaunchWithNoProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the application and load the program.
        /// </summary>
        public static string AvAppLaunchWithProgram {
            get {
                return ResourceManager.GetString("AvAppLaunchWithProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open installation folder.
        /// </summary>
        public static string AvAppOpenInstallationFolder {
            get {
                return ResourceManager.GetString("AvAppOpenInstallationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active processes: {0}.
        /// </summary>
        public static string AvAppProcessesActive {
            get {
                return ResourceManager.GetString("AvAppProcessesActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the command-line string.
        /// </summary>
        public static string CommandLineCopy {
            get {
                return ResourceManager.GetString("CommandLineCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can load the specified program. Studio project may be upgraded in the process, if their version is lower..
        /// </summary>
        public static string CompatibilityCompatibleDescription {
            get {
                return ResourceManager.GetString("CompatibilityCompatibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the program.
        /// </summary>
        public static string CompatibilityIncompatibleDescription {
            get {
                return ResourceManager.GetString("CompatibilityIncompatibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May load studio projects of earlier versions. User may be required to fix issues with changed ports..
        /// </summary>
        public static string CompatibilityOutdatedDescription {
            get {
                return ResourceManager.GetString("CompatibilityOutdatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of project is unknown - cannot determine compatibility.
        /// </summary>
        public static string CompatibilityUnknownDescription {
            get {
                return ResourceManager.GetString("CompatibilityUnknownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete source.
        /// </summary>
        public static string CustomSourceButtonDeleteTooltip {
            get {
                return ResourceManager.GetString("CustomSourceButtonDeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit source.
        /// </summary>
        public static string CustomSourceButtonEditTooltip {
            get {
                return ResourceManager.GetString("CustomSourceButtonEditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path did not match any app :-(.
        /// </summary>
        public static string CustomSourceEditorAppNotMatched {
            get {
                return ResourceManager.GetString("CustomSourceEditorAppNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CustomSourceEditorButtonCancel {
            get {
                return ResourceManager.GetString("CustomSourceEditorButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find folder through Explorer.
        /// </summary>
        public static string CustomSourceEditorButtonFolderPickerTooltip {
            get {
                return ResourceManager.GetString("CustomSourceEditorButtonFolderPickerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CustomSourceEditorButtonOK {
            get {
                return ResourceManager.GetString("CustomSourceEditorButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string CustomSourceEditorDescriptionHeader {
            get {
                return ResourceManager.GetString("CustomSourceEditorDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected App.
        /// </summary>
        public static string CustomSourceEditorDetectedAppHeader {
            get {
                return ResourceManager.GetString("CustomSourceEditorDetectedAppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide path to the main directory of the application.
        /// </summary>
        public static string CustomSourceEditorHeader {
            get {
                return ResourceManager.GetString("CustomSourceEditorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: .
        /// </summary>
        public static string CustomSourceEditorPathHeader {
            get {
                return ResourceManager.GetString("CustomSourceEditorPathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Path: .
        /// </summary>
        public static string CustomSourceEditorSourcePathHeader {
            get {
                return ResourceManager.GetString("CustomSourceEditorSourcePathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened on {0:yyyy-MM-dd HH:mm:ss}.
        /// </summary>
        public static string DatetimeOpenedOn {
            get {
                return ResourceManager.GetString("DatetimeOpenedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialogHeader {
            get {
                return ResourceManager.GetString("ErrorDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file does not exist..
        /// </summary>
        public static string ErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML file appears to be corrupted..
        /// </summary>
        public static string ErrorInvalidXml {
            get {
                return ResourceManager.GetString("ErrorInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine type of project..
        /// </summary>
        public static string ErrorUnknownFileType {
            get {
                return ResourceManager.GetString("ErrorUnknownFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is neither a project file nor a runtime executable..
        /// </summary>
        public static string ErrorUnrecognizedFile {
            get {
                return ResourceManager.GetString("ErrorUnrecognizedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by:  .
        /// </summary>
        public static string InstalledAppsGroupBy {
            get {
                return ResourceManager.GetString("InstalledAppsGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed applications.
        /// </summary>
        public static string InstalledAppsPageTitle {
            get {
                return ResourceManager.GetString("InstalledAppsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm termination of all process of app.
        /// </summary>
        public static string KillAllProcessesDialogHeader {
            get {
                return ResourceManager.GetString("KillAllProcessesDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to kill all process of app:.
        /// </summary>
        public static string KillAllProcessesDialogMessage {
            get {
                return ResourceManager.GetString("KillAllProcessesDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string KillProcessButtonNo {
            get {
                return ResourceManager.GetString("KillProcessButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string KillProcessButtonYes {
            get {
                return ResourceManager.GetString("KillProcessButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm termination of process.
        /// </summary>
        public static string KillProcessDialogHeader {
            get {
                return ResourceManager.GetString("KillProcessDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to kill this process:.
        /// </summary>
        public static string KillProcessDialogMessage {
            get {
                return ResourceManager.GetString("KillProcessDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line parameters.
        /// </summary>
        public static string LauncherCommandLineArgumentsSectionHeader {
            get {
                return ResourceManager.GetString("LauncherCommandLineArgumentsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with {0} .
        /// </summary>
        public static string LauncherLaunchWith {
            get {
                return ResourceManager.GetString("LauncherLaunchWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with {0} and close this launcher.
        /// </summary>
        public static string LauncherLaunchWithAndClose {
            get {
                return ResourceManager.GetString("LauncherLaunchWithAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line arguments:.
        /// </summary>
        public static string LaunchOptionsCommandLineString {
            get {
                return ResourceManager.GetString("LaunchOptionsCommandLineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close console after finished execution.
        /// </summary>
        public static string LaunchOptionsExecutorAutoCloseTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorAutoCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically closes the application when program is finished (only in console mode).
        /// </summary>
        public static string LaunchOptionsExecutorAutoCloseTooltip {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorAutoCloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console mode.
        /// </summary>
        public static string LaunchOptionsExecutorConsoleModeTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorConsoleModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the application in console mode, without HMI.
        /// </summary>
        public static string LaunchOptionsExecutorConsoleModeTooltip {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorConsoleModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level: .
        /// </summary>
        public static string LaunchOptionsExecutorLogLevelTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorLogLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the minimum log level that will be printed in the console.
        /// </summary>
        public static string LaunchOptionsExecutorLogLevelTooltip {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorLogLevelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log pipe:.
        /// </summary>
        public static string LaunchOptionsExecutorLogPipeTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorLogPipeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a named pipe which will be populated with log entries during application lifetime.
        /// </summary>
        public static string LaunchOptionsExecutorLogPipeTooltip {
            get {
                return ResourceManager.GetString("LaunchOptionsExecutorLogPipeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application does not have supported launch options..
        /// </summary>
        public static string LaunchOptionsNoOptions {
            get {
                return ResourceManager.GetString("LaunchOptionsNoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string LaunchOptionsResetButton {
            get {
                return ResourceManager.GetString("LaunchOptionsResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all arguments to default values.
        /// </summary>
        public static string LaunchOptionsResetButtonTooltip {
            get {
                return ResourceManager.GetString("LaunchOptionsResetButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application does not have customizable launch options..
        /// </summary>
        public static string LaunchOptionsStudioOptions {
            get {
                return ResourceManager.GetString("LaunchOptionsStudioOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening project.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring window to focus.
        /// </summary>
        public static string ProcessOverviewBringToFocus {
            get {
                return ResourceManager.GetString("ProcessOverviewBringToFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill process.
        /// </summary>
        public static string ProcessOverviewKill {
            get {
                return ResourceManager.GetString("ProcessOverviewKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy program path to clipboard.
        /// </summary>
        public static string ProgramDetailsCopyPath {
            get {
                return ResourceManager.GetString("ProgramDetailsCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified: .
        /// </summary>
        public static string ProgramDetailsDateModified {
            get {
                return ResourceManager.GetString("ProgramDetailsDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: .
        /// </summary>
        public static string ProgramDetailsLocation {
            get {
                return ResourceManager.GetString("ProgramDetailsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string ProgramDetailsLocationFallback {
            get {
                return ResourceManager.GetString("ProgramDetailsLocationFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open program folder.
        /// </summary>
        public static string ProgramDetailsOpenFolder {
            get {
                return ResourceManager.GetString("ProgramDetailsOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string ProgramDetailsProgramName {
            get {
                return ResourceManager.GetString("ProgramDetailsProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No program loaded.
        /// </summary>
        public static string ProgramDetailsProgramNameFallback {
            get {
                return ResourceManager.GetString("ProgramDetailsProgramNameFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: .
        /// </summary>
        public static string ProgramDetailsProjectType {
            get {
                return ResourceManager.GetString("ProgramDetailsProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string ProgramDetailsProjectTypeFallback {
            get {
                return ResourceManager.GetString("ProgramDetailsProjectTypeFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string ProgramDetailsSavedWithVersion {
            get {
                return ResourceManager.GetString("ProgramDetailsSavedWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string ProgramDetailsSavedWithVersionFallback {
            get {
                return ResourceManager.GetString("ProgramDetailsSavedWithVersionFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine version.
        /// </summary>
        public static string ProgramDetailsSavedWithVersionMissing {
            get {
                return ResourceManager.GetString("ProgramDetailsSavedWithVersionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio professional project.
        /// </summary>
        public static string ProjectProductTypeProfessionalLabel {
            get {
                return ResourceManager.GetString("ProjectProductTypeProfessionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime application.
        /// </summary>
        public static string ProjectProductTypeRuntimeLabel {
            get {
                return ResourceManager.GetString("ProjectProductTypeRuntimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;It&apos;s just a simple application, it can&apos;t take too long to code.&quot;.
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new custom source.
        /// </summary>
        public static string SettingsPageAddCustomSourceButton {
            get {
                return ResourceManager.GetString("SettingsPageAddCustomSourceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates (once a day).
        /// </summary>
        public static string SettingsPageCheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("SettingsPageCheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the app will check for updates after being launched for the first time during the day.
        /// </summary>
        public static string SettingsPageCheckForUpdatesOnStartupTooltip {
            get {
                return ResourceManager.GetString("SettingsPageCheckForUpdatesOnStartupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string SettingsPageCheckUpdatesButtonContent {
            get {
                return ResourceManager.GetString("SettingsPageCheckUpdatesButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom sources.
        /// </summary>
        public static string SettingsPageCustomSourcesHeader {
            get {
                return ResourceManager.GetString("SettingsPageCustomSourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File associations.
        /// </summary>
        public static string SettingsPageFileAssociationHeader {
            get {
                return ResourceManager.GetString("SettingsPageFileAssociationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository link (report bugs and improvements).
        /// </summary>
        public static string SettingsPageGithubLink {
            get {
                return ResourceManager.GetString("SettingsPageGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app folder.
        /// </summary>
        public static string SettingsPageOpenInstallationFolderButton {
            get {
                return ResourceManager.GetString("SettingsPageOpenInstallationFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the folder in which this app is installed.
        /// </summary>
        public static string SettingsPageOpenInstallationFolderButtonTooltip {
            get {
                return ResourceManager.GetString("SettingsPageOpenInstallationFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string SettingsPageOtherTitle {
            get {
                return ResourceManager.GetString("SettingsPageOtherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this app as default for all related extensions.
        /// </summary>
        public static string SettingsPageSetFileAssociationsButton {
            get {
                return ResourceManager.GetString("SettingsPageSetFileAssociationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets this app as the default app to open all vision project and runtime files.
        /// </summary>
        public static string SettingsPageSetFileAssociationsButtonTooltip {
            get {
                return ResourceManager.GetString("SettingsPageSetFileAssociationsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill all child windows.
        /// </summary>
        public static string ShellKillChildrenButton {
            get {
                return ResourceManager.GetString("ShellKillChildrenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ShellMenuFileHeader {
            get {
                return ResourceManager.GetString("ShellMenuFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ShellMenuItemFileExitHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open project....
        /// </summary>
        public static string ShellMenuItemFileSettingsOpenProject {
            get {
                return ResourceManager.GetString("ShellMenuItemFileSettingsOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ShellMenuItemFileSettingsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileSettingsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed _applications.
        /// </summary>
        public static string ShellMenuItemViewsInstalledAppsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsInstalledAppsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Launcher.
        /// </summary>
        public static string ShellMenuItemViewsLauncherPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsLauncherPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently opened files.
        /// </summary>
        public static string ShellMenuRecentFiles {
            get {
                return ResourceManager.GetString("ShellMenuRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Views.
        /// </summary>
        public static string ShellMenuViewsHeader {
            get {
                return ResourceManager.GetString("ShellMenuViewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a string..
        /// </summary>
        public static string ValidationArgumentHasToBeString {
            get {
                return ResourceManager.GetString("ValidationArgumentHasToBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contains double quotes..
        /// </summary>
        public static string ValidationArgumentNoDoubleQuotes {
            get {
                return ResourceManager.GetString("ValidationArgumentNoDoubleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contains single quotes..
        /// </summary>
        public static string ValidationArgumentNoSingleQuotes {
            get {
                return ResourceManager.GetString("ValidationArgumentNoSingleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain whitespace..
        /// </summary>
        public static string ValidationArgumentNoWhitespace {
            get {
                return ResourceManager.GetString("ValidationArgumentNoWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string VersionCheckDialogCancelButtonContent {
            get {
                return ResourceManager.GetString("VersionCheckDialogCancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables automatic checks.
        /// </summary>
        public static string VersionCheckDialogDisableAutoChecksButtonContent {
            get {
                return ResourceManager.GetString("VersionCheckDialogDisableAutoChecksButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version detected.
        /// </summary>
        public static string VersionCheckDialogHeader {
            get {
                return ResourceManager.GetString("VersionCheckDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open download page.
        /// </summary>
        public static string VersionCheckDialogLaunchPageButtonContent {
            get {
                return ResourceManager.GetString("VersionCheckDialogLaunchPageButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update ({0}) released at {1:yyyy-MM-dd} is available for download..
        /// </summary>
        public static string VersionCheckDialogMessageFormat {
            get {
                return ResourceManager.GetString("VersionCheckDialogMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The release title is: {0}.
        /// </summary>
        public static string VersionCheckDialogMessageSecondFormat {
            get {
                return ResourceManager.GetString("VersionCheckDialogMessageSecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates found.
        /// </summary>
        public static string VersionCheckDialogNoUpdatesHeader {
            get {
                return ResourceManager.GetString("VersionCheckDialogNoUpdatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉🎉 You have the newest version! 🎉🎉.
        /// </summary>
        public static string VersionCheckDialogNoUpdatesMessage {
            get {
                return ResourceManager.GetString("VersionCheckDialogNoUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        public static string VersionCheckDialogQuestion {
            get {
                return ResourceManager.GetString("VersionCheckDialogQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        public static string VersionCheckDialogSkipVersionButtonContent {
            get {
                return ResourceManager.GetString("VersionCheckDialogSkipVersionButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install update.
        /// </summary>
        public static string VersionCheckDialogUpdateButtonContent {
            get {
                return ResourceManager.GetString("VersionCheckDialogUpdateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is already running, you may not be able to start another process.
        /// </summary>
        public static string WarningLanchButtonWarningTooltip {
            get {
                return ResourceManager.GetString("WarningLanchButtonWarningTooltip", resourceCulture);
            }
        }
    }
}
