name: Release

on:
  pull_request:
    branches:
      - fake-release
    types: [closed]
  push:
    branches:
      - fake-release

jobs:
  publish:
    #if: >
    #  github.event.pull_request.merged == true &&
    #  (startsWith(github.event.pull_request.head.ref, 'release/') ||
    #   startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    defaults:
      run:
        shell: pwsh

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Confirm PowerShell 7 is available
        run: pwsh -v

      - name: Install Inno Setup
        run: |
          choco install innosetup --no-progress -y

      - name: Run publish script
        run: ./publish.ps1

      - name: Find built artifacts
        id: artifacts
        run: |
          $version = . ./publish_tools/get-version.ps1
          if (-not $version) {
            throw "Version not found"
          }else{
            Write-Host "Version is $version"
          }
          $releaseDir = Resolve-Path ./Release

          $zipPath = Get-ChildItem $releaseDir -Filter "*_${version}.zip" | Select-Object -First 1
          if (-not $zipPath) {
            throw "ZIP file not found for version $version"
          }else{
            Write-Host "Zip is $zipPath"
          }

          $installerPath = Get-ChildItem $releaseDir -Filter "*$version*installer.exe" | Select-Object -First 1
          if (-not $installerPath) {
            throw "Installer EXE not found for version $version"
          }else{
            Write-Host "Installer is $installerPath"
          }

          echo "zip=$($zipPath.FullName)" >> $env:GITHUB_OUTPUT
          echo "installer=$($installerPath.FullName)" >> $env:GITHUB_OUTPUT
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Test variables
        run: |
          Write-Host ${{ steps.version.outputs.version }}
          Write-Host ${{ steps.artifacts.outputs.zip }}
          Write-Host ${{ steps.version.outputs.installer }}


      - name: Create Test GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Okapi Launcher ${{ steps.version.outputs.version }}
          generate_release_notes: true
          draft: true
          files: |
            ${{ steps.artifacts.outputs.zip }}
            ${{ steps.artifacts.outputs.installer }}